from pathlib import Path

import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from vibepin.api.auth import router as auth_router
from vibepin.api.find import router as find_router
from vibepin.api.tryon import router as tryon_router
from vibepin.api.vibe import router as vibe_router

app = FastAPI(title="vibepin API", version="0.1.0")

_ROOT = Path(__file__).resolve().parent.parent  # repo root

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Lock down to your frontend domain in production
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth_router)
app.include_router(find_router)
app.include_router(vibe_router)
app.include_router(tryon_router)


@app.get("/health", tags=["meta"])
async def health():
    return {"status": "ok"}


@app.get("/", include_in_schema=False)
async def serve_index():
    return FileResponse(_ROOT / "index.html")


@app.get("/privacy", include_in_schema=False)
async def privacy_policy():
    from fastapi.responses import HTMLResponse
    html = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Privacy &amp; AI Policy — vibepin</title>
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,700;1,400&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&display=swap" rel="stylesheet"/>
  <style>
    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'DM Sans',sans-serif;background:#FDF7F4;color:#111;line-height:1.75;padding:60px 24px 100px;}
    .wrap{max-width:680px;margin:0 auto;}
    a.logo{font-family:'Playfair Display',serif;font-size:1.3rem;font-weight:700;color:#E60023;text-decoration:none;display:block;margin-bottom:48px;}
    a.logo em{font-style:italic;}
    .label{font-size:0.7rem;font-weight:600;letter-spacing:2.5px;text-transform:uppercase;color:#E60023;margin-bottom:12px;display:flex;align-items:center;gap:10px;}
    .label::before{content:'';width:20px;height:1.5px;background:#E60023;}
    h1{font-family:'Playfair Display',serif;font-size:2.4rem;font-weight:700;line-height:1.1;letter-spacing:-0.5px;margin-bottom:40px;}
    h1 em{font-style:italic;color:#E60023;}
    section{margin-bottom:36px;}
    h2{font-size:1rem;font-weight:600;color:#111;margin-bottom:8px;}
    p{font-size:0.92rem;color:#444;}
    footer{margin-top:60px;padding-top:24px;border-top:1px solid #E4D8D2;font-size:0.78rem;color:#888;}
    footer a{color:#E60023;text-decoration:none;}
  </style>
</head>
<body>
  <div class="wrap">
    <a href="/" class="logo">vibe<em>pin</em></a>
    <div class="label">legal</div>
    <h1>Privacy &amp; AI <em>Policy</em></h1>

    <section>
      <h2>We don't store your images</h2>
      <p>Photos you upload for virtual try-on or style analysis are processed in memory and discarded immediately after. We never save, log, or retain any images you submit.</p>
    </section>

    <section>
      <h2>AI-generated results are not perfect</h2>
      <p>All results — product matches, style recommendations, and try-on previews — are generated by AI and may be inaccurate, incomplete, or not reflect real product availability. Use them as inspiration, not as a guarantee.</p>
    </section>

    <section>
      <h2>Pinterest profile analysis</h2>
      <p>When you connect your Pinterest account, we access your public profile and pins solely to analyse your aesthetic. We do not store your Pinterest credentials, access token, or any personal profile data beyond your username for the duration of your session.</p>
    </section>

    <section>
      <h2>No account, no tracking</h2>
      <p>vibepin does not require a permanent account. We do not use cookies for tracking, sell your data to third parties, or build profiles on our users.</p>
    </section>

    <section>
      <h2>Third-party services</h2>
      <p>We use third-party AI APIs to power our features. Your image data may be transiently processed by these services solely to generate results — refer to their respective privacy policies for details.</p>
    </section>

    <section>
      <h2>Not affiliated with Pinterest</h2>
      <p>vibepin is an independent project and is not affiliated with, endorsed by, or sponsored by Pinterest, Inc.</p>
    </section>

    <footer>
      Last updated April 2026. &nbsp;·&nbsp; <a href="/">Back to vibepin</a>
    </footer>
  </div>
</body>
</html>"""
    return HTMLResponse(html)


def main():
    uvicorn.run("vibepin.main:app", host="0.0.0.0", port=8000, reload=True)


if __name__ == "__main__":
    main()
